// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXFsvLdCnm6-b4glh5pqEZ-yzJEhQ7Oc4',
    appId: '1:328801593805:web:c3d8d7e60055bd9a567c84',
    messagingSenderId: '328801593805',
    projectId: 'music-app-eecbe',
    authDomain: 'music-app-eecbe.firebaseapp.com',
    storageBucket: 'music-app-eecbe.firebasestorage.app',
    measurementId: 'G-MJCHE7RV8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVHZVtMFGApCi7GqR3AChinnP_5Z8fs50',
    appId: '1:328801593805:android:09e4ed2ca76ae66e567c84',
    messagingSenderId: '328801593805',
    projectId: 'music-app-eecbe',
    storageBucket: 'music-app-eecbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhsdLbLMmW-ydJKBjIyVMD623qmXNNDXY',
    appId: '1:328801593805:ios:cc5576a3f3d93683567c84',
    messagingSenderId: '328801593805',
    projectId: 'music-app-eecbe',
    storageBucket: 'music-app-eecbe.firebasestorage.app',
    iosClientId: '328801593805-molpirft7liako9scdo2tsov60ibubd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhsdLbLMmW-ydJKBjIyVMD623qmXNNDXY',
    appId: '1:328801593805:ios:cc5576a3f3d93683567c84',
    messagingSenderId: '328801593805',
    projectId: 'music-app-eecbe',
    storageBucket: 'music-app-eecbe.firebasestorage.app',
    iosClientId: '328801593805-molpirft7liako9scdo2tsov60ibubd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXFsvLdCnm6-b4glh5pqEZ-yzJEhQ7Oc4',
    appId: '1:328801593805:web:acf187fe1f75ecc3567c84',
    messagingSenderId: '328801593805',
    projectId: 'music-app-eecbe',
    authDomain: 'music-app-eecbe.firebaseapp.com',
    storageBucket: 'music-app-eecbe.firebasestorage.app',
    measurementId: 'G-1G6654QXB3',
  );

}